# Generated by Django 4.0 on 2022-02-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descriptions', models.TextField()),
                ('Initial_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
