# Generated by Django 4.0 on 2022-02-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_comment_list_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lists.category')),
            ],
        ),
    ]
