# Generated by Django 4.0 on 2022-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
